print('==== Desafio 4.1 ====\n')
some_thing = input('Digite algo:: ')
print('O tipo primitivo é ', type(some_thing))
print('Só tem espaços? ', some_thing.isspace())
print('É um número? ', some_thing.isnumeric())
print('É alphanumérico? ', some_thing.isalnum())
print('Está em maiúsculo? ', some_thing.isupper())
print('Está em minúsculo? ', some_thing.islower())
print('Está capitalizado? ', some_thing.istitle())